/bin/bash: /home/ubuntu/miniconda/envs/fsdp/lib/libtinfo.so.6: no version information available (required by /bin/bash)
`loss_type=None` was set in the config but it is unrecognised.Using the default loss: `ForCausalLMLoss`.
Traceback (most recent call last):
  File "/home/ubuntu/fs2/train_experiment/train_fsdp.py", line 154, in <module>
    main()
  File "/home/ubuntu/fs2/train_experiment/train_fsdp.py", line 144, in main
    hooked_transformer(batch["input_ids"].cpu())
  File "/home/ubuntu/miniconda/envs/fsdp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/miniconda/envs/fsdp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/miniconda/envs/fsdp/lib/python3.10/site-packages/transformer_lens/HookedTransformer.py", line 550, in forward
    residual = block(
  File "/home/ubuntu/miniconda/envs/fsdp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/miniconda/envs/fsdp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1581, in _call_impl
    hook_result = hook(self, args, result)
TypeError: main.<locals>.save_act() takes 2 positional arguments but 3 were given
srun: error: 192-222-55-57: task 0: Exited with exit code 1
